# Site settings
title: Peninsula Symphonic Winds
description: "A community concert band based in Palos Verdes, California"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pswinds.org" # the name of your domain
logo_url: svg/min/logo.svg
logo: /svg/min/logo.svg

# Hero
hero: 
    hero_img: psw_016.jpg
    hero_title: Peninsula Symphonic Winds

# Contact form
api_token: # Enter API token here

# rehearsal time/day
rehearsal:
    day: Wednesdays
    time: 7:45pm-10pm
    location: Los Angeles Harbor College<br>Music Building Room 107
    address: 1111 Figueroa Place, Wilmington CA 90744
    mapLink: https://www.google.com/maps/place/Los+Angeles+Harbor+College/data=!4m2!3m1!1s0x0:0x5de6b9ef8f42b374?sa=X&ved=0CCUQrwswAGoVChMI9qrNu-T_yAIVF_NjCh0BGQGW
    
# Social settings
social:
  links:
    - http://www.facebook.com/peninsulawinds/
    - http://twitter.com/peninsula_winds
facebook:
  publisher: http://www.facebook.com/peninsulawinds/
twitter: 
  username: peninsula_winds
#instagram: http://instagram.com
#youtube: http://youtube.com
#skype: skype:obaez_design?userinfo
#feed: yes

# Footer
copyright: Peninsula Symphonic Winds - All rights reserved

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore,
    svg
]

# Theme Settings
analytics: 
google_verification:
